### ISSUE TITLE
Sistema de Admin com votação + Menu Amigável

### ISSUE THREAD

**Issue by guiaugustinegri** [gmtandi/huetf#2]
Pra deixar o uso do apw absoleto.

Admin pode:

- Pede admin (console admin)
- Jogadores votam sim ou não
- Ao receber admin ele pode:
- Mudar o mapa
- Mudar o modo (Publico/partida)
- Iniciar partida
- Mudar detalhes partida ( ex tempo: timeup-down)

Pra facilitar operação do admin, tudo é feito num menu, ao ganhar o privilegio de ser admin na tela dele aparece as opções.

**Comment by gmtandi** [comment]
Votação para se tornar admin já existe no 1.45

-> elect

O servidor deve estar configurado com adminlevel:
  localinfo adminlevel [1/2]

-- 

Pensaremos na questão do menu_admin.

**Comment by gmtandi** [comment]
Adminmenu implementado;
A questão da votacao p/ virar admin já existia no OzTF.
Sobre fazer tudo no menu, algumas questões podem ser complicadas, mudar maps: no server temos 1502 maps. Fazer seleção de qual map vai ser via menu eh complicado. Teremos que pensar nisso outra hora, fechando..
