### ISSUE TITLE
ENGINEER - MELHORIAS

### ISSUE THREAD

**Issue by saculsoares** [gmtandi/huetf#4]
Upgrade/Repair/Restock quando der um hit com o spanner na Sentry Gun, sem passar por menu

**Comment by fdittz** [comment]
I'll borrow some code from Classic Fortress and make some modifications, but in the end it will work in a similar way to what they have done.

When you use you spanner on the sentry gun the game will try to execute an action without showing the menus, respecting this priorities: Try to Upgrade, Try to Repair and Try to reload.

1 - At first, if the sentry is not at level 3 and the engineer has enough cells, it will perform an upgrade (therefore restoring the HP and ammo to the max).
2 - If the sentry is on level 3 or the engineer doesn't have enough cells to upgrade it, it will check the Sentry Gun's HP and if it's not at the maximum levels, it will repair it.
3 - If upgrading is not possible (either Sentry is already on max level or the engineer doesn't have enough cells) and the Sentry Gun's HP is full, then it will check if it is full of ammo. If its not, it will reload the Sentry Gun until it's full again.

Finally if no upgrading, repairing and reloading is possible the game will show a menu with three options:
1. Rotate 45 degrees to the left
2. Rotate 180 degrees
3. Rotate 45 degrees to the right

I think in Classic Fortress this menu is persistent, but in HueTF you will need one Spanner Hit for each single rotation action

**Comment by gmtandi** [comment]
@fdittz  i think it is done yet? can we close this?
