### ISSUE TITLE
Mostrar barra de Armor e Life para classes suporte (MEDIC E ENG)

### ISSUE THREAD

**Issue by guiaugustinegri** [gmtandi/huetf#5]
Igual quando voce ve o demo, mas neste caso in game.
Vai ajudar o medic e eng a curarem.

**Comment by gmtandi** [comment]
Essa barra aparece do lado do Client somente em demo ou qtvplay - acredito não ser possível ativar server-side, possivelmente é provavel que seja necessária uma modificação no lado do client para que o server consiga ter controle sobre isso -

**Comment by gmtandi** [comment]
Not viable at the time. Closing issue...
