### ISSUE TITLE
How to join project

### ISSUE THREAD

**Issue by drzel** [gmtandi/huetf#6]
Hey guys, sorry to create an issue but I wasn't sure of the best way to contact you. I'm zel. Some of you might have used zelTF.

Anyway, I've been hoping to come across the oztf 1.45 source for a decade or more. I want to join this project. Do you have a communication system that you use?

Sorry I can't speak Portuguese, but Google translate works well for most things.

**Comment by gmtandi** [comment]
Hi DrZel,

It's a pleasure have you by here.

We are mainly on WhatsApp, do you have whatsapp? You can send to my email
(huehuehue)r

Thank you!!
[]'s,
Andi

**Comment by drzel** [comment]
Hey Andi,

Zel here. My number is (huehuehue). You should be able to reach me on WhatsApp with that.

Cheers

On 2 Apr. 2017 11:26 pm, gmtandi <notifications@github.com> wrote:
Hi DrZel,

It's a pleasure have you by here.

We are mainly on WhatsApp, do you have whatsapp? You can send to my email
(Huehuehue)

Thank you!!
[]'s,
Andi
